auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

# Enable OTLP log ingestion
otlp:
  enabled: true

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

limits_config:
  retention_period: 72h  # 3 days
  max_query_length: 72h  # Limit queries to retention period
  ingestion_rate_mb: 8   # Lower rate for local development
  ingestion_burst_size_mb: 16  # Lower burst for local