receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.namespace
        value: pocket-pal
        action: insert

  # Convert OTLP logs to Loki format
  attributes:
    actions:
      - key: loki.format
        value: json
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp/jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  # Use generic HTTP exporter for Loki with proper format
  otlphttp:
    endpoint: "http://loki:3100/loki/api/v1/push"
    headers:
      Content-Type: "application/json"
    tls:
      insecure: true
    compression: gzip

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/jaeger]

    logs:
      receivers: [otlp]
      processors: [resource, batch, attributes]
      exporters: [debug, otlphttp]
