receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.namespace
        value: pocket-pal
        action: insert

  # Transform logs to Loki format
  attributes:
    actions:
      - key: loki.tenant
        value: pocket-pal
        action: insert
      - key: loki.attribute.labels
        value: service.name,service.version,service.namespace
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp/jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  # Direct Loki exporter (the original working approach)
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "pocket-pal"
    labels:
      attributes:
        service.name: "service_name"
        service.version: "service_version"
        environment: "environment"
      resource:
        service.name: "service_name"

  debug:
    verbosity: normal

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/jaeger]

    logs:
      receivers: [otlp]
      processors: [resource, batch, attributes]
      exporters: [debug, loki]
