receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "shopping-service"
    labels:
      attributes:
        service.name: "service"
        service.version: "version"
      resource:
        service.name: "service"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    
    logs:
      receivers: [otlp]
      exporters: [loki]