receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: service.namespace
        value: pocket-pal
        action: insert

  # Transform logs to Loki format
  attributes:
    actions:
      - key: loki.tenant
        value: pocket-pal
        action: insert
      - key: loki.attribute.labels
        value: service.name,service.version,service.namespace
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp/jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  # Send logs to Loki via HTTP
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp/v1/logs"
    tls:
      insecure: true
    headers:
      "Content-Type": "application/x-protobuf"

  debug:
    verbosity: normal

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/jaeger]

    logs:
      receivers: [otlp]
      processors: [resource, batch, attributes]
      exporters: [debug, otlphttp/loki]
