server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # OTEL Collector JSON log files (shopping-service logs)
  - job_name: otel-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: otel-collector
          __path__: /var/log/otel/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: resourceLogs[0].scopeLogs[0].logRecords[0].timeUnixNano
            level: resourceLogs[0].scopeLogs[0].logRecords[0].severityText
            body: resourceLogs[0].scopeLogs[0].logRecords[0].body.stringValue
            service_name: resourceLogs[0].resource.attributes.service.name
            service_instance: resourceLogs[0].resource.attributes.service.instance.id
            environment: resourceLogs[0].resource.attributes.environment
      - labels:
          service_name:
          environment:
          level:
      - timestamp:
          source: timestamp
          format: Unix
      - output:
          source: body

  # STT Service Docker logs
  - job_name: stt-service
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["stt-service"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - target_label: 'job'
        replacement: 'stt-service'
      - target_label: 'service_name'
        replacement: 'stt-service'
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: time
            message: msg
      - labels:
          level:
          service_name:
      - timestamp:
          source: timestamp
          format: '2006-01-02T15:04:05.000000000Z'
          fallback_formats:
            - '2006-01-02T15:04:05Z'
            - RFC3339Nano
            - '2006-01-02 15:04:05'